#include "concrete_block_detector/detector_core_pipeline.hpp"
#include <gtest/gtest.h>
#include <algorithm>
namespace concrete_block_detector::detector_core {namespace {
Points synthetic_block_with_ground() {Points points; for (int x = -30; x <= 30; ++x) {for (int y = -30; y <= 30; ++y) {points.emplace_back(x * .04, y * .04, 0.);}} for (int x = 0; x <= 22; ++x) {for (int y = 0; y <= 15; ++y) {points.emplace_back(-.44 + x * .04, -.3 + y * .04, .6);}} for (int y = 0; y <= 15; ++y) {for (int z = 0; z <= 15; ++z) {points.emplace_back(.45, -.3 + y * .04, z * .04);}} return points;}
TEST(DetectorCorePipeline, VoxelOutputIsCanonicalAndInputOrderIndependent) {Points first{Point(.01,.01,.01), Point(.03,.03,.03), Point(.12,.01,.01)}; auto second = first; std::reverse(second.begin(), second.end()); const auto down_a = voxel_downsample(first, .1), down_b = voxel_downsample(second, .1); ASSERT_EQ(down_a.size(), 2U); ASSERT_EQ(down_a.size(), down_b.size()); EXPECT_NEAR((down_a[0] - down_b[0]).norm(), 0., 1e-12); EXPECT_NEAR(down_a[0].x(), .02, 1e-8);}
TEST(DetectorCorePipeline, ComposesGroundProposalPlaneAndSelectionStages) {DetectionParameters params; params.min_inliers = 30; params.ransac_iterations = 600; const auto result = detect_without_refinement(synthetic_block_with_ground(), params); EXPECT_GT(result.counts.downsampled_points, 100U); EXPECT_GT(result.counts.above_support_points, 100U); EXPECT_GE(result.counts.proposal_components, 1U); EXPECT_GT(result.counts.plane_fit_calls, 0U); EXPECT_GE(result.counts.raw_hypotheses, 1U); ASSERT_FALSE(result.poses.empty()); EXPECT_NEAR(result.poses.front().position.z(), .3, .06);}
TEST(DetectorCorePipeline, PreserveTopAxisRetainsPlaneTiltAndRefinedYaw) {const Eigen::Matrix3d initial = exp_so3(Point(.04, -.03, .20)); const Eigen::Matrix3d refined = exp_so3(Point(.20, -.15, .35)); const Eigen::Matrix3d guarded = preserve_top_axis(initial, refined); EXPECT_NEAR((guarded.col(2) - initial.col(2)).norm(), 0., 1e-12); EXPECT_NEAR(guarded.determinant(), 1., 1e-12); EXPECT_TRUE((guarded.transpose() * guarded).isApprox(Eigen::Matrix3d::Identity(), 1e-12));}
}}  // namespace concrete_block_detector::detector_core
